### ISSUE TITLE
Error on SelectionBuilder<>()

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [d4n3436/Fergun.Interactive#10]
Ran into an error when trying to use the SelectionBuilder. I copied the sample text from here and tried it, and I get this error:

```
App Command System.MissingMethodException: Method not found: 'System.Nullable`1<Int32> Discord.Net.HttpException.get_DiscordCode()'.
   at Fergun.Interactive.InteractiveService.ApplyActionOnStopAsync[TOption](IInteractiveElement`1 element, IInteractiveMessageResult result, SocketInteraction lastInteraction, SocketMessageComponent stopInteraction)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Fergun.Interactive.InteractiveService.ApplyActionOnStopAsync[TOption](IInteractiveElement`1 element, IInteractiveMessageResult result, SocketInteraction lastInteraction, SocketMessageComponent stopInteraction)
   at Fergun.Interactive.InteractiveService.WaitForSelectionResultAsync[TOption](SelectionCallback`1 callback)
   at Fergun.Interactive.InteractiveService.SendSelectionAsync[TOption](BaseSelection`1 selection, IMessageChannel channel, Nullable`1 timeout, IUserMessage message, Action`1 messageAction, CancellationToken cancellationToken)
   at ChefBotRDisc.Core.Modules.RecipeModule.Add() in C:\Projects\VS\DiscordBots\ChefBotRDisc\ChefBotRDisc.Core\Modules\RecipeModule.cs:line 96
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass10_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
```

I am using the SlashCommand Interactions with 3.4 Discord.Net Labs, not sure if that would cause this.

```
[SlashCommand("add", "Create new recipe. This will send a DM to you for further info.", false, RunMode.Async)]
public async Task Add()
{
    var options = new[] { "C", "C++", "C#", "Java", "Python", "JavaScript", "PHP" };

    var pageBuilder = new PageBuilder() // A PageBuilder is just an EmbedBuilder with a Text property (content).
        .WithTitle("Selection Example")
        .WithDescription($"Select a programming language:\n{string.Join('\n', options.Select(x => $"- **{x}**"))}")
        .WithColor(Color.Purple); // Random embed color.

    var selection = new SelectionBuilder<string>() // Create a new SelectionBuilder that uses strings as input.
        .AddUser(Context.User) // Only allow the user that executed the command to interact with the selection.
        .WithOptions(options) // Set the options.
        .WithInputType(InputType.Messages) // Use messages to receive the selection.
        .WithSelectionPage(pageBuilder) // Set the selection page, this is the page that will be displayed in the message.
        .WithDeletion(DeletionOptions.None) // By default, the selections delete valid inputs (messages, reactions) but you can change this behaviour.
        .Build(); // Build the SelectionBuilder.

    // Send the selection to the source channel and wait until it times out
    var result = await Interactive.SendSelectionAsync(selection, Context.Channel, TimeSpan.FromMinutes(1));

    // Get the selected option. This may be null/default if the selection times out or gets cancelled.
    string selected = result.Value;

    // You can check whether a selection failed or ended successfully with the Status property.
    // var status = result.Status;

    // You can also use the IsSuccess, IsCanceled and IsTimeout properties.
    bool isSuccess = result.IsSuccess;

    var builder = new EmbedBuilder()
        .WithDescription(isSuccess ? $"You selected: {selected}" : "Timeout!")
        .WithColor(Color.Purple);

    await ReplyAsync(embed: builder.Build());
}

```

**Comment by d4n3436** [comment]
Hi, I believe this error happens because of a breaking change from Labs in the type of `DiscordCode`, which is now an enum instead of an `int?`.

I can't investigate the issue further right now but updating `Fergun.Interactive.Labs` to version 1.3-dev may solve the issue.
Since this is a pre-release version you'll have to tick the "Include Pre-release" box in your IDE.
