### ISSUE TITLE
PageFactory ArgumentNullException

### ISSUE THREAD

**Issue by BlyZeDev** [d4n3436/Fergun.Interactive#37]
I'm trying to implement my own paginator that can have multiple batches of pages depending on the current Select Menu value.
I'm handling the interaction for the Select Menu here and set the current Pages index depending on the selected index
```cs
[ComponentInteraction(MobyCore.HelpSelectMenuId, TreatAsRegex = false)]
public async Task HelpSelectMenuInteraction(string selected)
{
    await DeferAsync(true);

    var interaction = (SocketMessageComponent)Context.Interaction;

    _interactive.TryGetPaginator(interaction.Message, out var paginator);

    if (paginator is MobySelectMenuPaginator selectMenuPaginator)
    {
        selectMenuPaginator.CurrentPageCollectionIndex = int.Parse(selected);
    }
}
```

I guess I'm doing it wrong because otherwise it would work xD.
How can I implement that correctly?

StackTrace
```cs
Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'properties.PageFactory')
   at Fergun.Interactive.InteractiveGuards.NotNull[T](T obj, String parameterName)
   at Fergun.Interactive.Pagination.BaseLazyPaginator..ctor(IBaseLazyPaginatorBuilderProperties properties)
   at Moby.Pagination.MobySelectMenuPaginator..ctor(IBaseLazyPaginatorBuilderProperties properties, Dictionary`2 pages) in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Pagination\MobySelectMenuPaginator.cs:line 17
   at Moby.Pagination.MobySelectMenuPaginatorBuilder.Build() in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Pagination\MobySelectMenuPaginatorBuilder.cs:line 18
   at Moby.Statics.MobyPaginators.GetHelpPaginator(IOrderedEnumerable`1 modules) in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Statics\MobyPaginators.cs:line 232
   at Moby.Statics.MobyPaginators.GetHelp(IReadOnlyCollection`1 modules) in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Statics\MobyPaginators.cs:line 23
   at Moby.Bot.OnReadyAsync() in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Bot.cs:line 144
   at Discord.EventExtensions.InvokeAsync(AsyncEvent`1 eventHandler)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Paginator Builder**
```cs
public sealed class MobySelectMenuPaginatorBuilder : BaseMobyPaginatorBuilder<MobySelectMenuPaginator, MobySelectMenuPaginatorBuilder>
{
    private Dictionary<int, IReadOnlyList<IPage>>? pages;

    public MobySelectMenuPaginatorBuilder WithSelectMenu(SelectMenuBuilder selectMenuBuilder, Dictionary<int, IReadOnlyList<IPage>> pages)
    {
        AddSelectMenu(selectMenuBuilder);

        this.pages = pages;
        return this;
    }

    public override MobySelectMenuPaginator Build() => new MobySelectMenuPaginator(this, pages);
}
```
**Paginator**
```cs
public sealed class MobySelectMenuPaginator : BaseLazyPaginator
{
    private readonly ConcurrentDictionary<int, IReadOnlyList<IPage>> _pages;

    public override Func<int, Task<IPage>> PageFactory { get; }

    public override int MaxPageIndex => Math.Clamp(_pages[CurrentPageCollectionIndex].Count - 1, 0, int.MaxValue);

    public int CurrentPageCollectionIndex { get; set; }

    public MobySelectMenuPaginator(IBaseLazyPaginatorBuilderProperties properties, Dictionary<int, IReadOnlyList<IPage>>? pages) : base(properties)
    {
        ArgumentNullException.ThrowIfNull(pages, nameof(pages));
        _pages = new ConcurrentDictionary<int, IReadOnlyList<IPage>>(pages);

        PageFactory = index => Task.FromResult(_pages[CurrentPageCollectionIndex][index]);
    }
}
```

**Comment by d4n3436** [comment]
Try setting the `PageFactory` in the builder instead.

**Comment by BlyZeDev** [comment]
But how can I use CurrentPageCollectionIndex then?

**Comment by BlyZeDev** [comment]
Why are these properties virtual if you have to set them beforehand? 😅

**Comment by BlyZeDev** [comment]
I changed to this but now I have other problems 🥲

When using the command the paginator with the select menu appears. When I change pages only the pages that are for a specific select menu options are displayed. But when I change the select menu option the embed won't update. It updates when I change pages but then the select menu resets back to the default option.

**Builder**
```cs
public sealed class MobySelectMenuPaginatorBuilder : PaginatorBuilder<MobySelectMenuPaginator, MobySelectMenuPaginatorBuilder>
{
    private Dictionary<int, IReadOnlyList<IPage>>? pages;

    public MobySelectMenuPaginatorBuilder WithStandardActions()
    {
        return WithActionOnCancellation(ActionOnStop.DeleteMessage)
            .WithActionOnTimeout(ActionOnStop.DeleteInput)
            .WithDeletion(DeletionOptions.Invalid);
    }

    public MobySelectMenuPaginatorBuilder AddStandardOptions()
    {
        return WithInputType(InputType.Buttons)
            .AddOption(new PaginatorButton("◀️", PaginatorAction.Backward, ButtonStyle.Primary))
            .AddOption(new PaginatorButton("🔢", PaginatorAction.Jump, ButtonStyle.Primary))
            .AddOption(new PaginatorButton("▶️", PaginatorAction.Forward, ButtonStyle.Primary)) //Emote.Parse("<:Moby:1313878953403875441>") Markdown of custom Emoji
            .AddOption(new PaginatorButton("🗑️", PaginatorAction.Exit, ButtonStyle.Danger));
    }

    public MobySelectMenuPaginatorBuilder WithSelectMenu(SelectMenuBuilder selectMenuBuilder, Dictionary<int, IReadOnlyList<IPage>>? pages)
    {
        AddSelectMenu(selectMenuBuilder);

        this.pages = pages;
        return this;
    }

    public override MobySelectMenuPaginator Build() => new MobySelectMenuPaginator(this, pages);
}
```
**Paginator**
```cs
public sealed class MobySelectMenuPaginator : Paginator
{
    private readonly ConcurrentDictionary<int, IReadOnlyList<IPage>> _pages;

    public override int MaxPageIndex => _pages[CurrentPageCollectionIndex].Count - 1;

    public int CurrentPageCollectionIndex { get; set; }

    public MobySelectMenuPaginator(IBasePaginatorBuilderProperties properties, Dictionary<int, IReadOnlyList<IPage>>? pages) : base(properties)
    {
        ArgumentNullException.ThrowIfNull(pages);
        if (pages.Any(x => x.Value.Count < 1)) throw new ArgumentException("All entries have to have at least one page", nameof(pages));
        
        _pages = new ConcurrentDictionary<int, IReadOnlyList<IPage>>(pages);
    }

    public override Task<IPage> GetOrLoadPageAsync(int pageIndex) => Task.FromResult(_pages[CurrentPageCollectionIndex][pageIndex]);
}
```
InteractionHandler
```cs
[ComponentInteraction(MobyCore.HelpSelectMenuId, TreatAsRegex = false)]
public async Task HelpSelectMenuInteraction(string selected)
{
    await DeferAsync(true);

    var interaction = (SocketMessageComponent)Context.Interaction;

    _interactive.TryGetPaginator(interaction.Message, out var paginator);

    if (paginator is MobySelectMenuPaginator selectMenuPaginator)
    {
        selectMenuPaginator.CurrentPageCollectionIndex = int.Parse(selected);
        await selectMenuPaginator.SetPageAsync(selectMenuPaginator.CurrentPageIndex);
    }
}
```

**Comment by d4n3436** [comment]
> It updates when I change pages but then the select menu resets back to the default option.

I believe you can change this in the select menu that you pass into the paginator builder. You'll probably need to use a select menu factory.

**Comment by BlyZeDev** [comment]
And why doesn't it update the current embed directly? It only updates after I pressed a paginator button

**Comment by d4n3436** [comment]
What you're trying to do is not supported on paginators by default, the select menus don't have the same behavior as buttons because they are "detached" from the paginator, meaning you have to handle them explicitly.

IIRC you can achieve the page switching by manually updating the message using `paginator.GetOrAddComponents()` and `paginator.GetOrLoadCurrentPageAsync()`.

**Comment by BlyZeDev** [comment]
Why doesn't this work tho?
I'm changing the index and then call `SetPageAsync` so the page should update?
Or why doesn't it update the page but if I use a button it updates the page on the embed
```cs
_interactive.TryGetPaginator(interaction.Message, out var paginator);

    if (paginator is MobySelectMenuPaginator selectMenuPaginator)
    {
        selectMenuPaginator.CurrentPageCollectionIndex = int.Parse(selected);
        await selectMenuPaginator.SetPageAsync(selectMenuPaginator.CurrentPageIndex);
    }
```

**Comment by d4n3436** [comment]
`SetPageAsync` just sets the index of the page internally. The paginator uses another method to update the message and embed. Use `interaction.UpdateAsync()` to manually update the message.

**Comment by BlyZeDev** [comment]
Ahh okay I'll try that, thank you :)

**Comment by BlyZeDev** [comment]
I'm using this now but I still don't find a way how to update the selectMenu so it doesn't defaults to the first entry.
**Paginator**
```cs
public sealed class MobySelectMenuPaginator : Paginator
{
    private readonly ConcurrentDictionary<int, IReadOnlyList<IPage>> _pages;

    private int currentPageCollectionIndex;

    public override int MaxPageIndex => _pages[currentPageCollectionIndex].Count - 1;

    public MobySelectMenuPaginator(IBasePaginatorBuilderProperties properties, Dictionary<int, IReadOnlyList<IPage>>? pages) : base(properties)
    {
        ArgumentNullException.ThrowIfNull(pages);
        if (pages.Any(x => x.Value.Count < 1)) throw new ArgumentException("All entries have to have at least one page", nameof(pages));
        
        _pages = new ConcurrentDictionary<int, IReadOnlyList<IPage>>(pages);
    }

    public override Task<IPage> GetOrLoadPageAsync(int pageIndex) => Task.FromResult(_pages[currentPageCollectionIndex][pageIndex]);

    public async Task UpdateAsync(SocketMessageComponent interaction, int collectionIndex)
    {
        Interlocked.Exchange(ref currentPageCollectionIndex, collectionIndex);

        CurrentPageIndex = 0;

        var currentPage = await GetOrLoadCurrentPageAsync().ConfigureAwait(false);
        var attachments = currentPage.AttachmentsFactory is null ? null : await currentPage.AttachmentsFactory().ConfigureAwait(false);
        var components = GetOrAddComponents(false).Build();

        await interaction.UpdateAsync(x =>
        {
            x.Content = currentPage.Text ?? "";
            x.Embeds = currentPage.GetEmbedArray();
            x.Components = components;
            x.AllowedMentions = currentPage.AllowedMentions;
            x.Attachments = attachments is null ? new Optional<IEnumerable<FileAttachment>>() : new Optional<IEnumerable<FileAttachment>>(attachments);
        }, null).ConfigureAwait(false);
    }
}
```
**Interaction**
```cs
[ComponentInteraction(MobyCore.HelpSelectMenuId, TreatAsRegex = false)]
public async Task HelpSelectMenuInteraction(string selected)
{
    var interaction = (SocketMessageComponent)Context.Interaction;

    _interactive.TryGetPaginator(interaction.Message, out var paginator);

    if (paginator is MobySelectMenuPaginator selectMenuPaginator)
    {
        await selectMenuPaginator.UpdateAsync(interaction, int.Parse(selected));
    }
}
```

**Comment by d4n3436** [comment]
As I mentioned before, you have to use a select menu factory to dynamically update the select menu. If you make `CurrentPageCollectionIndex` public and modify your `WithSelectMenu` method to accept a `Func<ISelectMenuContext, IPaginatorSelectMenu>`, then you can create a select menu that sets the default status of its options dynamically.

Here's an example code:

```c#
public async Task DefaultSelectMenu()
{
    List<IPage> pages1 =
    [
        new PageBuilder()
            .WithTitle("Page 1 of select menu 1")
            .WithColor(Color.Orange)
            .WithFooter("Page 1 of 2")
            .Build(),
        new PageBuilder()
            .WithTitle("Page 2 of select menu 1")
            .WithColor(Color.Orange)
            .WithFooter("Page 2 of 2")
            .Build()
    ];

    List<IPage> pages2 =
    [
        new PageBuilder()
            .WithTitle("Page 1 of select menu 2")
            .WithColor(Color.Orange)
            .WithFooter("Page 1 of 2")
            .Build(),
        new PageBuilder()
            .WithTitle("Page 2 of select menu 2")
            .WithColor(Color.Orange)
            .WithFooter("Page 2 of 2")
            .Build()
    ];

    Dictionary<int, IReadOnlyList<IPage>> pages = new()
    {
        { 0, pages1 },
        { 1, pages2 },
    };

    MobySelectMenuPaginator paginator = null!;
    paginator = new MobySelectMenuPaginatorBuilder()
        .WithStandardActions()
        .AddStandardOptions()
        .WithSelectMenu(SelectMenuFactory, pages)
        .Build();

    await _interactive.SendPaginatorAsync(paginator, Context.Interaction, TimeSpan.FromMinutes(10));

    IPaginatorSelectMenu SelectMenuFactory(ISelectMenuContext _)
    {
        var selectMenu = new SelectMenuBuilder().WithCustomId("custom_select_menu")
            .AddOption("Select menu 1", "0", isDefault: paginator.CurrentPageCollectionIndex == 0)
            .AddOption("Select menu 2", "1", isDefault: paginator.CurrentPageCollectionIndex == 1);

        return new PaginatorSelectMenu(selectMenu);
    }
}
```

**Comment by BlyZeDev** [comment]
I get another bug now using that solution.
I'll attach a short video.

https://github.com/user-attachments/assets/b50b3434-d838-41fe-9634-36cbd57b0ecd

This is the stack trace
```cs
Exception: Discord.Interactions.InteractionException: Error occurred executing help.
 ---> Discord.Net.HttpException: The server responded with error 10015: Unknown Webhook
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Fergun.Interactive.InteractiveService.ApplyActionOnStopAsync[TOption](IInteractiveElement`1 element, IInteractiveMessageResult result, IDiscordInteraction lastInteraction, SocketMessageComponent stopInteraction, Boolean deferInteraction)
   at Fergun.Interactive.InteractiveService.WaitForPaginatorResultAsync(PaginatorCallback callback)
   at Fergun.Interactive.InteractiveService.<>c__DisplayClass30_0.<<SendPaginatorAsync>g__WaitForPaginatorResultUsingCallbackAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Fergun.Interactive.InteractiveService.SendPaginatorAsync(Paginator paginator, IDiscordInteraction interaction, Nullable`1 timeout, InteractionResponseType responseType, Boolean ephemeral, Action`1 messageAction, Boolean resetTimeoutOnInput, CancellationToken cancellationToken)
   at Moby.Common.MobyModuleBase.SendPaginatorAsync(Paginator paginator) in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Common\MobyModuleBase.cs:line 57
   at Moby.Modules.GeneralModule.HelpCommand() in C:\Users\leons\OneDrive\Desktop\!Programmierung\Discord Bots\Moby Bot\Moby\Modules\GeneralModule.cs:line 29
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
```

**Comment by BlyZeDev** [comment]
Also it's not nice in my opinion that I can't hide the implementation, so I have to do this extra code every time I use the SelectMenuPaginator

**Comment by d4n3436** [comment]
> I get another bug now using that solution. I'll attach a short video.

I'm not sure what is causing the bug here. `ApplyActionOnStopAsync` is being called, probably because of the timeout. This updates the message using the last interaction it received. Perhaps it tried to update the message while you were pressing the button, causing some sort of race condition and invalidating the interaction the paginator callback had saved.

> Also it's not nice in my opinion that I can't hide the implementation, so I have to do this extra code every time I use the SelectMenuPaginator

You can certainly move the implementation to the paginator, it's just harder to do because it implies overriding the `HandleInteractionAsync` method, reimplement it (copy-paste) using the existing code and adding the new code.

**Comment by BlyZeDev** [comment]
I tested some more and it works perfectly fine except when I'm going to page 3 for example and select an option that has less then 3 pages. Then the buttons don't work correctly

**Comment by BlyZeDev** [comment]
Also when I'm using the command for the next time the pagination doesn't work at all I just get an embed

**Comment by BlyZeDev** [comment]
Maybe making SelectMenuFactories etc. overrideable

**Comment by BlyZeDev** [comment]
Got it to work while hiding away the complex stuff.
**Paginator**
```cs
public sealed class MobySelectMenuPaginator : Paginator
{
    private readonly ConcurrentDictionary<int, IReadOnlyList<IPage>> _pages;
    private readonly Func<ISelectMenuContext, IPaginatorSelectMenu> _selectMenuFactory;

    public int CurrentPageCollectionIndex { get; private set; }

    public override int MaxPageIndex => _pages[CurrentPageCollectionIndex].Count - 1;

    public MobySelectMenuPaginator(IBasePaginatorBuilderProperties properties, Dictionary<int, IReadOnlyList<IPage>>? pages, params IReadOnlyList<SelectMenuOption> options) : base(properties)
    {
        ArgumentNullException.ThrowIfNull(pages);
        if (pages.Any(x => x.Value.Count < 1)) throw new ArgumentException("All entries have to have at least one page", nameof(pages));
        
        _pages = new ConcurrentDictionary<int, IReadOnlyList<IPage>>(pages);
        _selectMenuFactory = SelectMenuFactory;

        IPaginatorSelectMenu SelectMenuFactory(ISelectMenuContext _)
        {
            var selectMenu = new SelectMenuBuilder().WithCustomId(MobyCore.HelpSelectMenuId);

            var counter = 0;
            foreach (var option in options)
            {
                selectMenu.AddOption(option.Label, option.Value, option.Description, option.Emote, CurrentPageCollectionIndex == counter++);
            }

            return new PaginatorSelectMenu(selectMenu);
        }
    }

    public override Task<IPage> GetOrLoadPageAsync(int pageIndex) => Task.FromResult(_pages[CurrentPageCollectionIndex][pageIndex]);

    public override ComponentBuilder GetOrAddComponents(bool disableAll, ComponentBuilder? builder = null)
    {
        builder ??= new ComponentBuilder();

        for (int i = 0; i < ButtonFactories.Count; i++)
        {
            var context = new ButtonContext(i, CurrentPageIndex, MaxPageIndex, disableAll);
            var properties = ButtonFactories[i].Invoke(context);

            if (properties is null || properties.IsHidden)
                continue;

            var style = properties.Style ?? (properties.Action == PaginatorAction.Exit ? ButtonStyle.Danger : ButtonStyle.Primary);
            var button = new ButtonBuilder();

            if (style == ButtonStyle.Link)
            {
                button.WithUrl(properties.Url);
            }
            else
            {
                button.WithCustomId(string.IsNullOrEmpty(properties.CustomId) ? $"{i}_{(int)properties.Action}" : properties.CustomId);
            }

            button.WithStyle(style)
                .WithEmote(properties.Emote)
                .WithDisabled(properties.IsDisabled ?? context.ShouldDisable(properties.Action));

            if (!string.IsNullOrEmpty(properties.Text))
                button.WithLabel(properties.Text);

            builder.WithButton(button);
        }

        {
            var context = new SelectMenuContext(0, CurrentPageIndex, MaxPageIndex, disableAll);
            var properties = _selectMenuFactory.Invoke(context);

            if (properties is not null && !properties.IsHidden)
            {
                var selectMenu = new SelectMenuBuilder(properties.CustomId, properties.Options, properties.Placeholder, properties.MaxValues,
                    properties.MinValues, properties.IsDisabled ?? context.ShouldDisable(), properties.Type, properties.ChannelTypes, properties.DefaultValues);

                builder.WithSelectMenu(selectMenu);
            }
        }

        return builder;
    }

    public async Task UpdateAsync(SocketMessageComponent interaction, int collectionIndex)
    {
        CurrentPageCollectionIndex = collectionIndex;

        CurrentPageIndex = 0;

        var currentPage = await GetOrLoadCurrentPageAsync().ConfigureAwait(false);
        var attachments = currentPage.AttachmentsFactory is null ? null : await currentPage.AttachmentsFactory().ConfigureAwait(false);
        var components = GetOrAddComponents(false).Build();

        await interaction.UpdateAsync(x =>
        {
            x.Content = currentPage.Text ?? "";
            x.Embeds = currentPage.GetEmbedArray();
            x.Components = components;
            x.AllowedMentions = currentPage.AllowedMentions;
            x.Attachments = attachments is null ? new Optional<IEnumerable<FileAttachment>>() : new Optional<IEnumerable<FileAttachment>>(attachments);
        }, null).ConfigureAwait(false);
    }
}
```
**PaginatorBuilder**
```cs
public sealed class MobySelectMenuPaginatorBuilder : PaginatorBuilder<MobySelectMenuPaginator, MobySelectMenuPaginatorBuilder>
{
    private readonly Dictionary<int, IReadOnlyList<IPage>>? _pages;
    private readonly IReadOnlyList<SelectMenuOption> _options;

    public MobySelectMenuPaginatorBuilder(Dictionary<int, IReadOnlyList<IPage>>? pages, params IReadOnlyList<SelectMenuOption> options)
    {
        _pages = pages;
        _options = options;
    }

    public MobySelectMenuPaginatorBuilder WithStandardActions()
    {
        return WithActionOnCancellation(ActionOnStop.DeleteMessage)
            .WithActionOnTimeout(ActionOnStop.DeleteInput)
            .WithDeletion(DeletionOptions.Invalid);
    }

    public MobySelectMenuPaginatorBuilder AddStandardOptions()
    {
        return WithInputType(InputType.Buttons)
            .AddOption(new PaginatorButton("◀️", PaginatorAction.Backward, ButtonStyle.Primary))
            .AddOption(new PaginatorButton("🔢", PaginatorAction.Jump, ButtonStyle.Primary))
            .AddOption(new PaginatorButton("▶️", PaginatorAction.Forward, ButtonStyle.Primary))
            .AddOption(new PaginatorButton("🗑️", PaginatorAction.Exit, ButtonStyle.Danger));
    }

    public override MobySelectMenuPaginator Build() => new MobySelectMenuPaginator(this, _pages, _options);
}
```
**Interaction**
```cs
[ComponentInteraction(MobyCore.HelpSelectMenuId, TreatAsRegex = false)]
public async Task HelpSelectMenuInteraction(string selected)
{
    var interaction = (SocketMessageComponent)Context.Interaction;

    _interactive.TryGetPaginator(interaction.Message, out var paginator);

    if (paginator is MobySelectMenuPaginator selectMenuPaginator)
    {
        await selectMenuPaginator.UpdateAsync(interaction, int.Parse(selected));
    }
}
```
**Usage**
```cs
private static MobySelectMenuPaginator GetHelpPaginator(IOrderedEnumerable<ModuleInfo> modules)
{
    ModuleInformationAttribute info;
    var selectMenuOptions = new List<SelectMenuOption>();
    var selectMenuPageCollection = new Dictionary<int, IReadOnlyList<IPage>>();

    var pages = new List<IPage>();
    foreach (var module in modules)
    {
        if (module.SlashCommands.Count == 0) continue;

        ProcessModule(module, pages);

        info = module.GetMobyInfo()!;
        selectMenuOptions.Add(new SelectMenuOptionBuilder(info.Name, info.Position.ToString(), info.Description, new Emoji(info.Emoji)).Build());
        selectMenuPageCollection.Add(info.Position, pages.ToList().AsReadOnly());

        pages.Clear();
    }

    return new MobySelectMenuPaginatorBuilder(selectMenuPageCollection, selectMenuOptions)
        .WithStandardActions()
        .WithFooter(PaginatorFooter.PageNumber)
        .AddStandardOptions()
        .Build();
}
```

**Comment by BlyZeDev** [comment]
When jumping it works correctly but throws this exception every time.
Any idea what causes this and how to fix that?
```json
{
  "Exceptions": [
    {
      "Type": "Discord.Net.HttpException",
      "Source": "Discord.Net.Rest",
      "Message": "The server responded with error 10062: Unknown interaction",
      "TargetSite": {
        "Type": "Discord.Net.Queue.RequestBucket\u002B\u003CSendAsync\u003Ed__20",
        "MemberType": "Method",
        "MemberName": "MoveNext"
      },
      "StackTrace": "   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)\r\n   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)\r\n   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)\r\n   at Discord.WebSocket.SocketModal.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options, PollProperties poll)\r\n   at Moby.Handlers.InteractionHandler.HandleInteractionAsync(SocketInteraction interaction) in C:\\Users\\leons\\OneDrive\\Desktop\\!Programmierung\\Discord Bots\\Moby Bot\\Moby\\Handlers\\InteractionHandler.cs:line 59"
    }
  ]
}
```

**Comment by BlyZeDev** [comment]
Nvm sometimes I get this as well:
```json
{
  "Exceptions": [
    {
      "Type": "System.Exception",
      "Source": null,
      "Message": "No Discord.Interactions.ModalCommandInfo found for 1322718244615884921",
      "StackTrace": null
    }
  ]
}
```

**Comment by d4n3436** [comment]
> When jumping it works correctly but throws this exception every time. Any idea what causes this and how to fix that?

Jumping works fine on my test code:

```c#
public async Task Test()
{
    var pages1 = Enumerable.Range(1, 3).Select(x => new PageBuilder()
        .WithTitle($"Page {x} of select menu 1")
        .WithColor(Color.Orange)
        .WithFooter($"Page {x} of 3")
        .Build()).ToList();

    var pages2 = Enumerable.Range(1, 3).Select(x => new PageBuilder()
        .WithTitle($"Page {x} of select menu 2")
        .WithColor(Color.Orange)
        .WithFooter($"Page {x} of 3")
        .Build()).ToList();

    Dictionary<int, IReadOnlyList<IPage>> pages = new()
    {
        { 0, pages1 },
        { 1, pages2 }
    };

    var options = new List<SelectMenuOption>
    {
        new SelectMenuOptionBuilder().WithLabel("Select menu 1").WithValue("0").Build(),
        new SelectMenuOptionBuilder().WithLabel("Select menu 2").WithValue("1").Build(),
    };

    var paginator = new MobySelectMenuPaginatorBuilder(pages, options)
        .WithStandardActions()
        .WithFooter(PaginatorFooter.PageNumber)
        .AddStandardOptions()
        .Build();

    await _interactive.SendPaginatorAsync(paginator, Context.Interaction, TimeSpan.FromSeconds(60));
}
```

> Nvm sometimes I get this as well:

This looks like a bug in your interaction handler. The jump prompt modal belongs to the paginator so it doesn't know what to do.

**Comment by BlyZeDev** [comment]
That's in my Interaction Handler
```cs
private async Task HandleInteractionAsync(SocketInteraction interaction)
    {
        if (interaction is SocketMessageComponent component && component.Data.Type is ComponentType.Button)
        {
            if (_interactive.IsManaged(interaction)) return;
        }

        try
        {
            var context = new SocketInteractionContext(_client, interaction);
            var result = await _service.ExecuteCommandAsync(context, _provider);

            if (!result.Error.HasValue) return;
            
            await context.Interaction.RespondAsync(result.ErrorReason, ephemeral: true);

            _logger.LogError(result.ErrorReason, new Exception(result.ErrorReason));
        }
        catch (Exception ex)
        {
            _logger.LogError("Error when handling interaction", ex);

            if (interaction.Type is InteractionType.ApplicationCommand)
                await (await interaction.GetOriginalResponseAsync()).DeleteAsync();
        }
    }
```

**Comment by BlyZeDev** [comment]
It seems pretty random to me which error is thrown when

**Comment by d4n3436** [comment]
Try checking if the interaction is a `SocketModal` and call `_interactive.IsManaged` to filter it.

**Comment by BlyZeDev** [comment]
Yep that worked, thank you ^^
```cs
private async Task HandleInteractionAsync(SocketInteraction interaction)
{
    switch (interaction)
    {
        case SocketModal:
        case SocketMessageComponent component when component.Data.Type is ComponentType.Button:
            if (_interactive.IsManaged(interaction)) return;
            break;
    }
    
    //...
}
```
